name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd nodejs-demoapp-main/nodejs-demoapp-main
          npm install

      - name: Run tests
        run: |
          cd nodejs-demoapp-main/nodejs-demoapp-main
          npm test

      - name: Build Docker image
        run: |
          cd nodejs-demoapp-main/nodejs-demoapp-main
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-demoapp:${{ github.sha }} .

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push Docker image
        run: |
          cd nodejs-demoapp-main/nodejs-demoapp-main
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-demoapp:${{ github.sha }}
